name: Nuke Release
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
          
      - name: Checkout Coni-lang
        run: |
          git clone https://gitea.hellonico.info/hellonico/coni-lang.git $(pwd)/coni-lang
          
      - name: Setup NPKM
        uses: coni-lang/npkm/.github/actions/setup-npkm@main
        with:
          version: 'build-8'
          asset-name: 'npkm-coni-release-2026-06-03-0948.zip'
          
      - name: Build and Package Release
        run: |
          CONI_HOME=$(pwd)/coni-lang npkm package_release.edn
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          files: dist/*.zip
          generate_release_notes: true
